language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get github.com/mitchellh/gox
  - $GOPATH/bin/dep ensure

after_success:
  - test -n "$TRAVIS_TAG" && make release